### ISSUE TITLE
Steps to reproduce unhandled memory error

### ISSUE THREAD

**Issue by zyd-n** [zyd-n/nohgl#1]
You need to have glfw installed on your machine and you MUST use SLIME.

Ubuntu/Debian: `sudo apt install libglfw3 libglfw3-dev`
Fedora: `sudo dnf install glfw glfw-devel`
Arch: `sudo pacman -S glfw`

Steps to reproduce:

```
git clone -b buggy-compile https://github.com/zyd-n/nohgl ~/common-lisp/nohgl
```

From your Lisp session in Emacs, make sure to set the directory to the nohgl dir.

```
CL-USER> (swank:set-default-directory "~/common-lisp/nohgl")
CL-USER> (ql-dist:install-dist "http://dist.shirakumo.org/shirakumo.txt") ; Might need it, might not
CL-USER> (ql:quickload :nohgl)
CL-USER> (in-package :nohgl.bug)
CL-USER> (start-bug)
```
A window should have launched. Note that it might look as if you can't use your REPL but just press `Enter` once. From here you should do the following:

1. Open the file `~/common-lisp/nohgl/renders/bug.lisp` - You should see three forms that start with `defvao`. Take each of these and enter them one by one in the REPL. You should see the triangles in the window change color.

2. After you have have verified that they do in fact change color when entered at the REPL, go back to the file and place your point/cursor at any one of the forms and try to compile it via `C-c C-c`. You should get a unhandled memory fault error.

**Comment by veer66** [comment]
Is there any package used jemalloc and loaded using dlopen?

**Comment by zyd-n** [comment]
> Is there any package used jemalloc and loaded using dlopen?

I don't understand your question.

**Comment by veer66** [comment]
> > Is there any package used jemalloc and loaded using dlopen?
> 
> I don't understand your question.

I mean perhaps glfw is linked with jemalloc, and it causes the trouble.

**Comment by zyd-n** [comment]
> > > Is there any package used jemalloc and loaded using dlopen?
> > 
> > 
> > I don't understand your question.
> 
> I mean perhaps glfw is linked with jemalloc, and it causes the trouble.

Ah, I don't think it is. After someone pointed it out, I think the issue boils down to how contexts work in OpenGL with threads.

**Comment by zyd-n** [comment]
Fixed in https://github.com/zyd-n/nohgl/commit/c7314bbffe9f84a0ed29dc9c160ad62d211c15e3
